@echo off
echo Checking for process on port 3000...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":3000" ^| find "LISTENING"') do (
    echo Killing process %%a...
    taskkill /f /pid %%a
)
echo Starting Backend Server...
cd src
node app.js
